name: e2e Tests
on: push
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: yarn

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # - uses: browser-actions/setup-firefox@latest
    # - run: firefox --version

    - name: Create testing project
      run: yarn test:create-project

    - name: Start server
      run: yarn test:start

    - name: Run tests
      run: yarn test





    # - uses: actions/setup-node@v2
    #   with:
    #     node-version: '16.x'
    # - name: Install dependencies
    #   run: yarn
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
    # - name: Run Playwright tests
    #   run: yarn playwright test
    # - uses: actions/upload-artifact@v2
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30
