name: e2e Tests
on: push

env:
  GCLOUD_CLIENT_ID: ${{ secrets.GCLOUD_CLIENT_ID }}
  GCLOUD_CLIENT_SECRET: ${{ secrets.GCLOUD_CLIENT_SECRET }}
  GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
  GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
  # NODE_ENV: development

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: yarn

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Create testing project
      run: yarn test:create-project

    - name: Start server
      run: yarn test:start --no-log

    - name: Dump logs once the tests ended
      uses: webiny/action-post-run@2.0.1
      id: dump-pm2-logs
      with:
        run: yarn pm2 logs --nostream --lines 100000 test-project

    - name: Run tests
      run: yarn test

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 2